import {
  useCallback,
  useEffect,
  useLayoutEffect,
  useRef,
  useState,
  type ClipboardEvent,
  type CSSProperties,
  type DragEvent,
  type KeyboardEvent
} from "react";
import { createPortal } from "react-dom";
import ReactMarkdown from "react-markdown";
import {
  ArrowUp,
  ArrowUpRight,
  Check,
  ChevronDown,
  CircleAlert,
  Clock3,
  Copy,
  HeartPulse,
  History,
  ImagePlus,
  LoaderCircle,
  MoonStar,
  Palette,
  Trash2,
  SquarePen,
  Square,
  Terminal,
  X,
  type LucideIcon
} from "lucide-react";
import type { CorosLinkApi } from "../coroslink-api";
import type {
  WatchfaceAiChatSummary,
  WatchfaceAiEvent,
  WatchfaceAiMessage,
  WatchfaceAiMemory,
  WatchfaceAiOptions
} from "../../electron/watchfaceAutomationTypes";
import { WatchmakerDial } from "./WatchmakerDial";
import "./watchfaceAi.css";

interface ToolStep {
  callId: string;
  tool: string;
  status: "call" | "done" | "failed";
  message?: string;
}

interface PanelMessage {
  memory?: WatchfaceAiMemory;
  id: string;
  role: "user" | "assistant";
  content: string;
  images: string[];
  imageRole?: "design-reference" | "diagnostic";
  steps: ToolStep[];
  previews: string[];
  generated: GeneratedImage[];
  thinking: string;
  error?: string;
  errorCode?: "CODEX_CLI_NOT_FOUND" | "CODEX_CLI_UNAVAILABLE";
  authError?: boolean;
  streaming?: boolean;
  cancelled?: boolean;
  changed?: boolean;
}


interface GeneratedImage {
  assetId: string;
  width: number;
  height: number;
  dataUrl: string;
}

function WatchmakerError({ message }: { message: PanelMessage }) {
  // Recognize older saved errors too; new runs carry a stable error code.
  const missing = message.errorCode === "CODEX_CLI_NOT_FOUND" || message.error?.startsWith("Codex CLI was not found.");
  const unavailable = message.errorCode === "CODEX_CLI_UNAVAILABLE" || message.error?.startsWith("Codex launchers were found, but none passed the launch check.");
  if (!missing && !unavailable) return <div className="wf-ai-error-card" role="alert"><CircleAlert size={14} aria-hidden="true" /><span>{message.error}</span></div>;
  return <div className="wf-ai-cli-setup" role="alert">
    <div className="wf-ai-cli-setup-heading"><Terminal size={17} aria-hidden="true" /><strong>{missing ? "Codex CLI needs to be installed" : "Codex CLI needs repair"}</strong></div>
    <p>{missing
      ? "CorosLink couldn’t find Codex CLI on this computer. It’s a separate terminal app required by this engine."
      : "CorosLink found Codex CLI, but it couldn’t start. The installation may be incomplete or out of date."}</p>
    <ol>
      <li><a href="https://learn.chatgpt.com/docs/codex/cli#getting-started" target="_blank" rel="noopener noreferrer">{missing ? "Follow OpenAI’s installation steps" : "Update or reinstall using OpenAI’s guide"}<ArrowUpRight size={12} aria-hidden="true" /></a> for your operating system.</li>
      <li>Open Terminal (PowerShell on Windows), run <code>codex</code>, and follow the sign-in prompts.</li>
      <li>Return here and send your message again.</li>
    </ol>
    <p className="wf-ai-cli-setup-note">Your face and chat are still here. Once Codex CLI is ready, send your message again.</p>
    <details><summary>Technical details</summary><pre>{message.error}</pre></details>
  </div>;
}

function GeneratedArtwork({ image, copyImage }: { image: GeneratedImage; copyImage: (assetId: string) => Promise<void> }) {
  const [status, setStatus] = useState<"idle" | "copying" | "copied" | "error">("idle");
  const [error, setError] = useState("");
  useEffect(() => {
    if (status !== "copied") return;
    const timer = window.setTimeout(() => setStatus("idle"), 2000);
    return () => window.clearTimeout(timer);
  }, [status]);
  const copy = async () => {
    setStatus("copying");
    setError("");
    try {
      await copyImage(image.assetId);
      setStatus("copied");
    } catch (caught) {
      setError(caught instanceof Error ? caught.message : "Could not copy the original image. Try again.");
      setStatus("error");
    }
  };
  return (
    <figure>
      <img src={image.dataUrl} alt="Image generated by Watchmaker" />
      <button type="button" className="wf-ai-copy-image" onClick={() => void copy()} disabled={status === "copying"}
        aria-label={status === "copied" ? "Image copied" : `Copy image (${image.width} by ${image.height} pixels)`}
        title={status === "copied" ? "Copied" : "Copy full-resolution image"}>
        {status === "copying" ? <LoaderCircle size={13} className="wf-ai-spin" aria-hidden="true" />
          : status === "copied" ? <Check size={13} aria-hidden="true" /> : <Copy size={13} aria-hidden="true" />}
        <span>{status === "copied" ? "Copied" : "Copy"}</span>
      </button>
      <figcaption>{image.width}×{image.height}</figcaption>
      <span className="wf-ai-copy-status" role="status">{status === "copied" ? "Image copied to clipboard" : ""}</span>
      {error ? <div className="wf-ai-copy-error" role="alert">{error}</div> : null}
    </figure>
  );
}

const TOOL_LABELS: Record<string, [running: string, done: string]> = {
  inspect_asset: ["Inspecting artwork", "Inspected artwork"],
  update_plan: ["Planning the edit", "Updated the plan"],
  review_generated_assets: ["Comparing artwork with your reference", "Reviewed artwork against your reference"],
  update_requirements: ["Recording your requirements", "Recorded your requirements"],
  review_requirements: ["Checking your requirements", "Reviewed your requirements"],
  continue_work: ["Continuing the design", "Continuing while progress is being made"],
  get_schema: ["Reading the editor schema", "Read the editor schema"],
  get_context: ["Checking the editor", "Checked the editor"],
  get_document: ["Reading the design", "Read the design"],
  apply_commands: ["Editing the face", "Edited the face"],
  select: ["Selecting layers", "Selected layers"],
  undo: ["Undoing", "Undid a step"],
  redo: ["Redoing", "Redid a step"],
  set_view: ["Changing the view", "Changed the view"],
  render_preview: ["Rendering a preview", "Rendered a preview"],
  get_geometry: ["Measuring the layout", "Measured the layout"],
  check_contrast: ["Checking contrast", "Checked contrast"],
  sample_color: ["Sampling colors", "Sampled colors"],
  recolor_image: ["Recoloring an image", "Recolored an image"],
  render_svg: ["Drawing vector artwork", "Drew vector artwork"],
  validate: ["Validating", "Validated"],
  build_archive: ["Building the archive", "Built the archive"],
  list_fonts: ["Listing fonts", "Listed fonts"],
  import_asset: ["Importing an image", "Imported an image"],
  generate_image: ["Generating an image", "Generated an image"],
  crop_image: ["Cropping an image", "Cropped an image"],
  save: ["Saving the project", "Saved the project"]
};

const SUGGESTIONS: Array<{ text: string; icon: LucideIcon }> = [
  { text: "Make the time larger and center it", icon: Clock3 },
  { text: "Restyle this face with a dark, sporty palette", icon: Palette },
  { text: "Add heart rate and steps below the time", icon: HeartPulse },
  { text: "Check the always-on display for legibility", icon: MoonStar }
];

const MAX_ATTACHMENTS = 4;
const MAX_IMAGE_EDGE = 1024;
const CLI_WARNING_KEY = "coroslink.watchfaceAi.cliWarningAcknowledged.v1";

function newId(): string {
  return typeof crypto !== "undefined" && "randomUUID" in crypto
    ? crypto.randomUUID()
    : `${Date.now()}-${Math.random().toString(36).slice(2)}`;
}

function readPreference(key: string): string {
  try { return window.localStorage.getItem(key) ?? ""; } catch { return ""; }
}

function writePreference(key: string, value: string): void {
  try { window.localStorage.setItem(key, value); } catch { /* preference only */ }
}

/** Decodes any pasted image and re-encodes it as a bounded PNG data URL. */
async function toPngDataUrl(file: Blob): Promise<string> {
  const bitmap = await createImageBitmap(file);
  try {
    const scale = Math.min(1, MAX_IMAGE_EDGE / Math.max(bitmap.width, bitmap.height));
    const canvas = document.createElement("canvas");
    canvas.width = Math.max(1, Math.round(bitmap.width * scale));
    canvas.height = Math.max(1, Math.round(bitmap.height * scale));
    canvas.getContext("2d")!.drawImage(bitmap, 0, 0, canvas.width, canvas.height);
    return canvas.toDataURL("image/png");
  } finally {
    bitmap.close();
  }
}

/** Rebuilds panel messages from a saved chat, tolerating older or partial shapes. */
function restoreMessages(raw: unknown[]): PanelMessage[] {
  const strings = (value: unknown) =>
    Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : [];
  return raw.flatMap((item) => {
    if (!item || typeof item !== "object") return [];
    const message = item as Partial<PanelMessage>;
    if (message.role !== "user" && message.role !== "assistant") return [];
    return [{
      id: typeof message.id === "string" ? message.id : newId(),
      role: message.role,
      content: typeof message.content === "string" ? message.content : "",
      images: strings(message.images),
      ...(message.imageRole ? { imageRole: message.imageRole } : {}),
      steps: Array.isArray(message.steps) ? message.steps.filter((step) => step && typeof step.tool === "string") : [],
      previews: strings(message.previews),
      generated: Array.isArray(message.generated)
        ? message.generated.filter((image) => image && typeof image.assetId === "string" && typeof image.dataUrl === "string")
        : [],
      thinking: "",
      ...(message.memory?.version === 1 && Array.isArray(message.memory.entries) ? { memory: message.memory } : {}),
      ...(typeof message.error === "string" ? { error: message.error } : {}),
      ...(["CODEX_CLI_NOT_FOUND", "CODEX_CLI_UNAVAILABLE"].includes(message.errorCode ?? "") ? { errorCode: message.errorCode } : {}),
      ...(message.cancelled ? { cancelled: true } : {}),
      ...(message.changed ? { changed: true } : {})
    }];
  });
}

function chatTitle(messages: PanelMessage[]): string {
  const first = messages.find((message) => message.role === "user");
  const text = first?.content.trim().replace(/\s+/g, " ");
  if (text) return text.length > 60 ? `${text.slice(0, 57)}…` : text;
  return first?.images.length ? "Image reference" : "New chat";
}

function relativeTime(iso: string): string {
  const then = Date.parse(iso);
  if (!Number.isFinite(then)) return "";
  const minutes = Math.round((Date.now() - then) / 60_000);
  if (minutes < 1) return "Just now";
  if (minutes < 60) return `${minutes}m ago`;
  const hours = Math.round(minutes / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.round(hours / 24);
  if (days < 7) return `${days}d ago`;
  return new Date(then).toLocaleDateString();
}

function stepLabel(step: ToolStep): string {
  const labels = TOOL_LABELS[step.tool];
  if (!labels) return step.tool;
  return step.status === "call" ? `${labels[0]}…` : step.status === "done" ? labels[1] : `${labels[0]} failed`;
}

/**
 * The hero dial, charged like lume: a sunburst disc catching a slow band of
 * light, a green-to-ice halo turning behind the bezel and one pip in orbit.
 */
function WatchmakerOrb() {
  return (
    <div className="wf-ai-orb wf-ai-enter" aria-hidden="true">
      <span className="wf-ai-orb-sunburst" />
      <span className="wf-ai-orb-light" />
      <span className="wf-ai-orb-halo" />
      <span className="wf-ai-orb-track" />
      <span className="wf-ai-orb-pip" />
      <WatchmakerDial size={92} hands />
    </div>
  );
}

/** Collapsible record of what Watchmaker did during one reply. */
function Activity({ message }: { message: PanelMessage }) {
  const [open, setOpen] = useState(false);
  const failed = message.steps.filter((step) => step.status === "failed").length;
  const running = [...message.steps].reverse().find((step) => step.status === "call");
  const summary = message.streaming
    ? running ? stepLabel(running) : "Working…"
    : `${message.steps.length} ${message.steps.length === 1 ? "step" : "steps"}${failed ? ` · ${failed} retried` : ""}`;
  return (
    <div className={`wf-ai-activity${open ? " is-open" : ""}`}>
      <button type="button" className="wf-ai-activity-toggle" onClick={() => setOpen((value) => !value)} aria-expanded={open}>
        {/* While streaming, the byline dial already shows Watchmaker working. */}
        {message.streaming ? null : <Check size={13} aria-hidden="true" />}
        <span className={message.streaming ? "wf-ai-shimmer" : undefined}>{summary}</span>
        <ChevronDown size={13} className="wf-ai-activity-chevron" aria-hidden="true" />
      </button>
      {open ? (
        <ol className="wf-ai-steps">
          {message.steps.map((step) => (
            <li key={step.callId} className={`is-${step.status}`}>
              <span className="wf-ai-step-icon" aria-hidden="true">
                {step.status === "call"
                  ? <LoaderCircle size={11} className="wf-ai-spin" />
                  : step.status === "done" ? <Check size={11} /> : <CircleAlert size={11} />}
              </span>
              <span className="wf-ai-step-body">
                {stepLabel(step)}
                {step.message ? <code>{step.message.length > 400 ? `${step.message.slice(0, 400)}…` : step.message}</code> : null}
              </span>
            </li>
          ))}
        </ol>
      ) : null}
    </div>
  );
}

/** Codex CLI chat, editing the open face through the automation bridge. */
export function WatchfaceAiPanel({
  api,
  hidden,
  projectKey,
  headingSlot,
  onBusyChange
}: {
  api: CorosLinkApi;
  hidden: boolean;
  /** Scopes saved chats to the open project (or draft). */
  projectKey: string;
  /** The pane heading's action area; chat controls render there when given. */
  headingSlot?: HTMLElement | null;
  /** Lets the editor show Watchmaker working on the AI tab from anywhere. */
  onBusyChange?: (busy: boolean) => void;
}) {
  const [messages, setMessages] = useState<PanelMessage[]>([]);
  const [draft, setDraft] = useState("");
  const [attachments, setAttachments] = useState<string[]>([]);
  const [attachmentRole, setAttachmentRole] = useState<"design-reference" | "diagnostic" | null>(null);
  const referenceMessage = [...messages].reverse().find(message => message.images.length && message.imageRole === "design-reference")
    ?? messages.find(message => message.images.length && message.imageRole !== "diagnostic");
  const hasReference = Boolean(referenceMessage) || messages.some(message => message.memory?.designReferenceIds?.length);
  const nextImageRole = attachmentRole ?? (hasReference ? "diagnostic" : "design-reference");
  const [attachError, setAttachError] = useState<string | null>(null);
  const [dragging, setDragging] = useState(false);
  const [cliWarningAcknowledged, setCliWarningAcknowledged] = useState(() => readPreference(CLI_WARNING_KEY) === "true");
  const [chatId, setChatId] = useState<string | null>(null);
  const [savedChats, setSavedChats] = useState<WatchfaceAiChatSummary[]>([]);
  const [historyOpen, setHistoryOpen] = useState(false);
  const [saveError, setSaveError] = useState<string | null>(null);
  const [activeRequest, setActiveRequest] = useState<string | null>(null);
  const activeRef = useRef<string | null>(null);
  const dirtyRef = useRef(false);
  const chatIdRef = useRef<string | null>(null);
  const saveQueueRef = useRef<Promise<void>>(Promise.resolve());
  const chatActionRef = useRef(0);
  const projectKeyRef = useRef(projectKey);
  projectKeyRef.current = projectKey;
  const savedKeyRef = useRef(projectKey);
  const historyRef = useRef<HTMLDivElement>(null);
  const logRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const fileRef = useRef<HTMLInputElement>(null);
  const stickToBottom = useRef(true);

  const updateAssistant = useCallback((requestId: string, update: (message: PanelMessage) => PanelMessage) => {
    setMessages((current) => current.map((message) => (message.id === requestId ? update(message) : message)));
  }, []);

  const finish = useCallback(() => {
    activeRef.current = null;
    setActiveRequest(null);
  }, []);

  useEffect(() => () => {
    if (activeRef.current) void api.cancelWatchfaceAi(activeRef.current);
    activeRef.current = null;
    chatActionRef.current++;
  }, [api]);

  useEffect(() => api.onWatchfaceAiEvent((event: WatchfaceAiEvent) => {
    if (event.requestId !== activeRef.current) return;
    const id = event.requestId;
    switch (event.type) {
      case "memory":
        updateAssistant(id, (message) => ({ ...message, memory: event.memory }));
        break;
      case "token":
        updateAssistant(id, (message) => ({ ...message, content: message.content + event.delta }));
        break;
      case "thinking":
        updateAssistant(id, (message) => ({ ...message, thinking: (message.thinking + event.delta).slice(-400) }));
        break;
      case "tool":
        updateAssistant(id, (message) => {
          const known = message.steps.some((step) => step.callId === event.callId);
          const next = { callId: event.callId, tool: event.tool, status: event.status, ...(event.message ? { message: event.message } : {}) };
          return {
            ...message,
            thinking: "",
            steps: known
              ? message.steps.map((step) => (step.callId === event.callId ? next : step))
              : [...message.steps, next]
          };
        });
        break;
      case "preview":
        updateAssistant(id, (message) => ({ ...message, previews: [...message.previews.slice(-2), event.dataUrl] }));
        break;
      case "generated":
        updateAssistant(id, (message) => ({
          ...message,
          generated: [...message.generated, { assetId: event.assetId, width: event.width, height: event.height, dataUrl: event.dataUrl }]
        }));
        break;
      case "done":
        updateAssistant(id, (message) => ({
          ...message,
          streaming: false,
          thinking: "",
          ...(event.cancelled ? { cancelled: true } : {}),
          ...(event.changed ? { changed: true } : {})
        }));
        dirtyRef.current = true;
        finish();
        break;
      case "error":
        updateAssistant(id, (message) => ({
          ...message,
          streaming: false,
          thinking: "",
          error: event.message,
          ...(event.code ? { errorCode: event.code } : {}),
          ...(event.authError ? { authError: true } : {})
        }));
        dirtyRef.current = true;
        finish();
        break;
      default:
        break;
    }
  }), [api, finish, updateAssistant]);

  useEffect(() => {
    onBusyChange?.(activeRequest !== null);
  }, [activeRequest, onBusyChange]);

  const refreshChats = useCallback(async () => {
    try {
      const chats = await api.listWatchfaceAiChats(projectKey);
      if (projectKeyRef.current === projectKey) setSavedChats(chats);
    } catch {
      if (projectKeyRef.current === projectKey) setSavedChats([]);
    }
  }, [api, projectKey]);

  useEffect(() => { void refreshChats(); }, [refreshChats]);

  const persist = useCallback((list: PanelMessage[], key: string) => {
    if (!list.length) return;
    // Reserve the identity before IPC and serialize writes. A late save must
    // never attach its id to a new chat or overwrite a newer reply.
    const id = chatIdRef.current ?? newId();
    chatIdRef.current = id;
    const save = saveQueueRef.current.then(async () => {
      try {
        const summary = await api.saveWatchfaceAiChat({
          id,
          projectKey: key,
          title: chatTitle(list),
          // Transient UI state isn't worth keeping.
          messages: list.map(({ thinking: _thinking, streaming: _streaming, ...rest }) => rest)
        });
        if (chatIdRef.current !== id || projectKeyRef.current !== key) return;
        savedKeyRef.current = key;
        setChatId(summary.id);
        setSaveError(null);
        void refreshChats();
      } catch (caught) {
        if (chatIdRef.current === id && projectKeyRef.current === key) {
          setSaveError(caught instanceof Error ? caught.message : "This chat couldn't be saved.");
        }
      }
    });
    saveQueueRef.current = save;
    return save;
  }, [api, refreshChats]);

  // Autosave once each reply settles.
  useEffect(() => {
    if (activeRequest || !dirtyRef.current) return;
    dirtyRef.current = false;
    void persist(messages, projectKey);
  }, [activeRequest, messages, persist, projectKey]);

  // A draft that gets saved as a project keeps its conversation.
  useEffect(() => {
    if (savedKeyRef.current === projectKey) return;
    if (chatIdRef.current && !activeRef.current) void persist(messages, projectKey);
    else savedKeyRef.current = projectKey;
    // Only react to the key changing.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [projectKey]);

  useEffect(() => {
    if (!historyOpen) return;
    const close = (event: PointerEvent) => {
      if (!historyRef.current?.contains(event.target as Node)) setHistoryOpen(false);
    };
    document.addEventListener("pointerdown", close);
    return () => document.removeEventListener("pointerdown", close);
  }, [historyOpen]);

  const openChat = async (id: string) => {
    if (activeRef.current) return;
    const action = ++chatActionRef.current;
    setHistoryOpen(false);
    try {
      await saveQueueRef.current;
      const chat = await api.loadWatchfaceAiChat(id);
      if (chatActionRef.current !== action) return;
      chatIdRef.current = chat.id;
      setChatId(chat.id);
      setMessages(restoreMessages(chat.messages));
      stickToBottom.current = true;
    } catch (caught) {
      if (chatActionRef.current !== action) return;
      setSaveError(caught instanceof Error ? caught.message : "That chat couldn't be opened.");
      void refreshChats();
    }
  };

  const removeChat = async (id: string) => {
    await saveQueueRef.current;
    await api.deleteWatchfaceAiChat(id).catch(() => undefined);
    if (chatIdRef.current === id) {
      chatIdRef.current = null;
      setChatId(null);
      setMessages([]);
    }
    void refreshChats();
  };

  useLayoutEffect(() => {
    const log = logRef.current;
    if (log && stickToBottom.current) log.scrollTop = log.scrollHeight;
  }, [messages]);

  // Grow the composer with its content up to a comfortable cap.
  useLayoutEffect(() => {
    const input = inputRef.current;
    if (!input) return;
    input.style.height = "auto";
    input.style.height = `${Math.min(input.scrollHeight, 200)}px`;
  }, [draft, hidden]);

  const addFiles = async (files: Iterable<File>) => {
    const images = [...files].filter((file) => file.type.startsWith("image/"));
    if (!images.length) return;
    setAttachError(null);
    const room = MAX_ATTACHMENTS - attachments.length;
    if (room <= 0) {
      setAttachError(`Attach up to ${MAX_ATTACHMENTS} images per message.`);
      return;
    }
    try {
      const encoded = await Promise.all(images.slice(0, room).map(toPngDataUrl));
      setAttachments((current) => [...current, ...encoded].slice(0, MAX_ATTACHMENTS));
      if (images.length > room) setAttachError(`Attach up to ${MAX_ATTACHMENTS} images per message.`);
    } catch {
      setAttachError("That image couldn't be read.");
    }
  };

  const send = (text: string) => {
    const content = text.trim();
    if ((!content && attachments.length === 0) || activeRef.current) return;
    chatActionRef.current++;
    const requestId = newId();
    const images = attachments;
    const history: WatchfaceAiMessage[] = [
      ...messages
        .filter((message) => message.content.trim() || message.images.length || message.memory)
        .map((message) => ({
          role: message.role,
          content: message.error ? `${message.content}\n[Previous attempt stopped: ${message.error}]` : message.cancelled ? `${message.content}\n[Previous attempt cancelled.]` : message.content,
          ...(message.memory ? { memory: message.memory } : {}),
          ...(message.images.length ? { images: message.images, imageRole: message.imageRole } : {}),
          ...(message.generated.length ? { generatedAssetIds: message.generated.map((image) => image.assetId) } : {})
        })),
      { role: "user", content, ...(images.length ? { images, imageRole: nextImageRole } : {}) }
    ];
    setMessages((current) => [
      ...current.map(message => images.length && nextImageRole === "design-reference" && message.imageRole === "design-reference" ? { ...message, imageRole: "diagnostic" as const } : message),
      { id: newId(), role: "user", content, images, imageRole: nextImageRole, steps: [], previews: [], generated: [], thinking: "" },
      { id: requestId, role: "assistant", content: "", images: [], steps: [], previews: [], generated: [], thinking: "", streaming: true }
    ]);
    setDraft("");
    setAttachments([]);
    setAttachmentRole(null);
    setAttachError(null);
    stickToBottom.current = true;
    activeRef.current = requestId;
    setActiveRequest(requestId);
    const options: WatchfaceAiOptions = {
      harness: "codex-cli"
    };
    api.sendWatchfaceAi(requestId, history, options).catch((caught: unknown) => {
      updateAssistant(requestId, (message) => ({
        ...message,
        streaming: false,
        error: caught instanceof Error ? caught.message : "Could not reach Watchmaker."
      }));
      dirtyRef.current = true;
      finish();
    });
  };

  const stop = () => {
    if (activeRequest) void api.cancelWatchfaceAi(activeRequest);
  };

  const newChat = () => {
    if (activeRequest) return;
    chatActionRef.current++;
    chatIdRef.current = null;
    setChatId(null);
    setHistoryOpen(false);
    setMessages([]);
    inputRef.current?.focus();
  };

  const onKeyDown = (event: KeyboardEvent<HTMLTextAreaElement>) => {
    // Keep editor shortcuts (delete, arrows, undo) from acting on the canvas.
    event.stopPropagation();
    if (event.key === "Enter" && !event.shiftKey && !event.nativeEvent.isComposing) {
      event.preventDefault();
      send(draft);
    }
  };

  const onPaste = (event: ClipboardEvent<HTMLTextAreaElement>) => {
    const files = [...event.clipboardData.files].filter((file) => file.type.startsWith("image/"));
    if (!files.length) return;
    event.preventDefault();
    void addFiles(files);
  };

  const onDrop = (event: DragEvent<HTMLDivElement>) => {
    event.preventDefault();
    setDragging(false);
    void addFiles(event.dataTransfer.files);
  };

  const busy = activeRequest !== null;
  const canSend = Boolean(draft.trim() || attachments.length) && !busy;

  const chatControls = (
    <div className="wf-ai-chat-controls">
      <div className="wf-ai-history" ref={historyRef}>
        <button
          type="button"
          className={`wf-ai-icon${historyOpen ? " is-active" : ""}`}
          onClick={() => {
            if (!historyOpen) void refreshChats();
            setHistoryOpen((open) => !open);
          }}
          disabled={busy}
          aria-expanded={historyOpen}
          title="Saved chats"
          aria-label="Saved chats"
        >
          <History size={15} aria-hidden="true" />
        </button>
        {historyOpen ? (
          <div className="wf-ai-history-menu" role="menu" aria-label="Saved chats for this face">
            <p className="wf-ai-history-heading">Chats for this face</p>
            {savedChats.length === 0 ? (
              <p className="wf-ai-history-empty">No saved chats yet. Conversations save automatically.</p>
            ) : (
              <ul>
                {savedChats.map((chat) => (
                  <li key={chat.id} className={chat.id === chatId ? "is-current" : undefined}>
                    <button type="button" role="menuitem" className="wf-ai-history-open" onClick={() => void openChat(chat.id)}>
                      <span>{chat.title}</span>
                      <small>{relativeTime(chat.updatedAt)}</small>
                    </button>
                    <button
                      type="button"
                      className="wf-ai-history-delete"
                      onClick={() => void removeChat(chat.id)}
                      aria-label={`Delete chat ${chat.title}`}
                      title="Delete chat"
                    >
                      <Trash2 size={13} aria-hidden="true" />
                    </button>
                  </li>
                ))}
              </ul>
            )}
          </div>
        ) : null}
      </div>
      <button
        type="button"
        className="wf-ai-icon"
        onClick={newChat}
        disabled={busy || messages.length === 0}
        title="New chat"
        aria-label="New chat"
      >
        <SquarePen size={15} aria-hidden="true" />
      </button>
    </div>
  );

  return (
    <div
      className={`wf-ai-panel${dragging ? " is-dragging" : ""}`}
      hidden={hidden}
      onDragOver={(event) => {
        if ([...event.dataTransfer.items].some((item) => item.type.startsWith("image/"))) {
          event.preventDefault();
          setDragging(true);
        }
      }}
      onDragLeave={(event) => {
        if (!event.currentTarget.contains(event.relatedTarget as Node | null)) setDragging(false);
      }}
      onDrop={onDrop}
    >
      <div
        className="wf-ai-log"
        ref={logRef}
        aria-live="polite"
        onScroll={(event) => {
          const log = event.currentTarget;
          stickToBottom.current = log.scrollHeight - log.scrollTop - log.clientHeight < 48;
        }}
      >
        {messages.length === 0 ? (
          <div className="wf-ai-hero is-bench">
            <WatchmakerOrb />
            <p className="wf-ai-caliber wf-ai-enter">
              <span className="wf-ai-live" />
              <b>Codex CLI</b>
            </p>
            <strong className="wf-ai-enter">What should we change?</strong>
            <p className="wf-ai-enter">Codex CLI edits the canvas live, one undoable step at a time. Save when you like the result.</p>
            <div className="wf-ai-suggestions">
              {SUGGESTIONS.map(({ text, icon: Icon }, index) => (
                <button
                  key={text}
                  type="button"
                  className="wf-ai-enter"
                  style={{ "--wf-ai-enter-i": index + 4 } as CSSProperties}
                  onClick={() => send(text)}
                >
                  <span className="wf-ai-suggestion-icon" aria-hidden="true"><Icon size={14} /></span>
                  <span>{text}</span>
                  <ArrowUpRight size={14} aria-hidden="true" />
                </button>
              ))}
            </div>
          </div>
        ) : messages.map((message) => message.role === "user" ? (
          <div key={message.id} className="wf-ai-turn is-user">
            {message.images.length ? (
              <div className="wf-ai-user-images">
                {message.images.map((image, index) => <img key={index} src={image} alt={`Attachment ${index + 1}`} />)}
                <button type="button" disabled={busy} onClick={() => setMessages(current => current.map(item => item.id === message.id
                  ? { ...item, imageRole: "design-reference" }
                  : item.imageRole === "design-reference" ? { ...item, imageRole: "diagnostic" } : item))}>
                  {message.imageRole === "design-reference" ? "Design reference" : "Use as design reference"}
                </button>
              </div>
            ) : null}
            {message.content ? <div className="wf-ai-bubble">{message.content}</div> : null}
          </div>
        ) : (
          <div key={message.id} className="wf-ai-turn is-assistant">
            <span className="wf-ai-byline">
              <WatchmakerDial size={14} working={Boolean(message.streaming)} />
              Watchmaker
            </span>
            {message.steps.length ? <Activity message={message} /> : null}
            {message.memory?.requirements?.length ? (
              <details className="wf-ai-requirements" open={message.streaming || undefined}>
                <summary>Requirements · {message.memory.requirements.filter((item) => item.status === "verified").length}/{message.memory.requirements.filter((item) => item.status !== "superseded").length} checked</summary>
                <ul>
                  {message.memory.requirements.map((item) => (
                    <li key={item.id} data-status={item.status}>
                      <strong>{item.requirement}</strong>
                      <span>{({ pending: "Pending", implemented: "Needs verification", verified: item.kind === "visual" || item.visualTargets?.length ? "Visually assessed · AI" : "Evidence reviewed · AI", blocked: "Blocked", superseded: "Changed by your request" })[item.status]}</span>
                      {item.detail ? <p>{item.detail}</p> : null}
                      {item.visualTargets?.map(target => <p key={target.id}>{target.label} · {target.dynamic ? "Live component" : "Appearance"}{target.appearance === "ring" ? " · ring" : ""}</p>)}
                      {item.visualFindings?.filter(finding => finding.verdict !== "matched" || finding.remainingDifferences?.length).map(finding => <p key={finding.targetId}>Remaining: {finding.remainingDifferences?.join("; ") || finding.verdict}</p>)}
                    </li>
                  ))}
                </ul>
              </details>
            ) : null}
            {message.generated.length ? (
              <div className="wf-ai-generated">
                {message.generated.map((image) => (
                  <GeneratedArtwork key={image.assetId} image={image} copyImage={api.copyWatchfaceAiImage} />
                ))}
              </div>
            ) : null}
            {message.previews.length ? (
              <div className="wf-ai-previews">
                {message.previews.map((preview, index) => (
                  <img
                    key={index}
                    src={preview}
                    alt="Preview rendered by Watchmaker"
                    className={index === message.previews.length - 1 ? "is-latest" : undefined}
                  />
                ))}
              </div>
            ) : null}
            {message.content ? (
              <div className="wf-ai-markdown"><ReactMarkdown>{message.content}</ReactMarkdown></div>
            ) : null}
            {message.streaming && !message.content && !message.steps.some((step) => step.status === "call") ? (
              <p className="wf-ai-thinking">
                <span className="wf-ai-shimmer">
                  {message.thinking.trim() ? message.thinking.trim().split("\n").pop() : "Thinking…"}
                </span>
              </p>
            ) : null}
            {message.changed && !message.streaming ? (
              <p className="wf-ai-note"><Check size={12} aria-hidden="true" /> Applied to the canvas. Undo from the toolbar, save when ready.</p>
            ) : null}
            {message.cancelled ? <p className="wf-ai-note">Stopped.</p> : null}
            {message.error ? (
              <WatchmakerError message={message} />
            ) : null}
          </div>
        ))}
      </div>

      <div className="wf-ai-composer-wrap">
        {referenceMessage ? <div className="wf-ai-design-reference">
          <img src={referenceMessage.images[0]} alt="Selected design reference" />
          <span>Design reference saved · new images default to troubleshooting</span>
        </div> : null}
        <div className={`wf-ai-composer${busy ? " is-working" : ""}`}>
          {attachments.length ? (
            <div className="wf-ai-attachments">
              <label>Use images as <select aria-label="Attachment purpose" value={nextImageRole} onChange={event => setAttachmentRole(event.target.value as "design-reference" | "diagnostic")}>
                <option value="design-reference">Design reference</option>
                <option value="diagnostic">Troubleshooting screenshots</option>
              </select></label>
              {attachments.map((image, index) => (
                <div key={index} className="wf-ai-attachment">
                  <img src={image} alt={`Attachment ${index + 1}`} />
                  <button
                    type="button"
                    aria-label={`Remove attachment ${index + 1}`}
                    onClick={() => setAttachments((current) => current.filter((_, other) => other !== index))}
                  >
                    <X size={10} aria-hidden="true" />
                  </button>
                </div>
              ))}
            </div>
          ) : null}
          <div className="wf-ai-harness">
            <span className="wf-ai-harness-label">Engine</span>
            <span className="wf-ai-harness-value"><Terminal size={14} aria-hidden="true" />Codex CLI</span>
            <span className="wf-ai-harness-hint">Uses your local CLI settings</span>
          </div>
          {!cliWarningAcknowledged ? <div className="wf-ai-cli-warning" role="note">
            <p>Codex CLI uses your local CLI sign-in and model settings. It can run shell commands, read local files, write to its work folder and temporary files, and access the network. Shell changes are outside editor Undo. Editor tools connect through MCP. Image generation still needs CorosLink’s ChatGPT sign-in.</p>
            <button type="button" onClick={() => {
              setCliWarningAcknowledged(true);
              writePreference(CLI_WARNING_KEY, "true");
              inputRef.current?.focus();
            }}>Continue</button>
          </div> : null}
          <textarea
            ref={inputRef}
            value={draft}
            rows={1}
            placeholder={busy ? "Watchmaker is working…" : "Describe a change, or paste an image…"}
            aria-label="Message Watchmaker"
            onChange={(event) => setDraft(event.target.value)}
            onKeyDown={onKeyDown}
            onPaste={onPaste}
          />
          <div className="wf-ai-toolbar">
            <button
              type="button"
              className="wf-ai-icon"
              onClick={() => fileRef.current?.click()}
              disabled={attachments.length >= MAX_ATTACHMENTS}
              title="Attach images"
              aria-label="Attach images"
            >
              <ImagePlus size={15} aria-hidden="true" />
            </button>
            <input
              ref={fileRef}
              type="file"
              accept="image/png,image/jpeg,image/webp,image/gif"
              multiple
              hidden
              onChange={(event) => {
                if (event.target.files) void addFiles(event.target.files);
                event.target.value = "";
              }}
            />
            <span className="wf-ai-cli-model">CLI model · sandboxed</span>
            <span className="wf-ai-toolbar-spacer" />
            {busy ? (
              <button type="button" className="wf-ai-send is-stop" onClick={stop} aria-label="Stop" title="Stop">
                <Square size={10} fill="currentColor" aria-hidden="true" />
              </button>
            ) : (
              <button type="button" className="wf-ai-send" onClick={() => send(draft)} disabled={!canSend} aria-label="Send" title="Send">
                <ArrowUp size={15} aria-hidden="true" />
              </button>
            )}
          </div>
        </div>
        {attachError ? <p className="wf-ai-error wf-ai-attach-error" role="alert">{attachError}</p> : null}
        {saveError ? <p className="wf-ai-error wf-ai-attach-error" role="alert">{saveError}</p> : null}
      </div>
      {hidden ? null : headingSlot ? createPortal(chatControls, headingSlot) : <div className="wf-ai-inline-controls">{chatControls}</div>}
      {dragging ? <div className="wf-ai-dropzone" aria-hidden="true"><ImagePlus size={20} /> Drop images for Watchmaker</div> : null}
    </div>
  );
}
