import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import electron from "electron";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, "..");
const buildDir = path.join(rootDir, "build");
const sourceArg = process.argv[2];
const defaultSource = path.join(buildDir, "icon.svg");
const sourcePath = path.resolve(sourceArg ?? defaultSource);

if (!fs.existsSync(sourcePath)) {
  console.error(`Icon source not found: ${sourcePath}`);
  process.exit(1);
}

fs.mkdirSync(buildDir, { recursive: true });

const svgSource = path.extname(sourcePath).toLowerCase() === ".svg"
  ? fs.readFileSync(sourcePath, "utf8")
  : undefined;
if (svgSource && (!svgSource.includes('id="sync-circle"') || !svgSource.includes("  <defs>"))) {
  throw new Error('The SVG source must contain <defs> and a group with id="sync-circle".');
}

const iconPngPath = path.join(buildDir, "icon.png");
// Render with the same SVG engine as the app, including bevels and filters.
// The helper also accepts PNG sources for the existing custom-source workflow.
const renderEnv = { ...process.env };
delete renderEnv.ELECTRON_RUN_AS_NODE;
execFileSync(electron, [path.join(__dirname, "render-icon.cjs"), sourcePath, iconPngPath], {
  stdio: "inherit",
  env: renderEnv,
  timeout: 30_000,
});

if (svgSource) {
  const motionStyle = `  <style>
    /* Generated by npm run icons:generate; edit icon.svg for the artwork. */
    #sync-circle {
      transform-box: view-box;
      transform-origin: 789.45px 702.65px;
      animation: coroslink-sync 6s linear infinite;
    }
    @keyframes coroslink-sync {
      to { transform: rotate(360deg); }
    }
    @media (prefers-reduced-motion: reduce) {
      #sync-circle { animation: none; }
    }
  </style>
`;
  fs.writeFileSync(path.join(buildDir, "icon-animated.svg"), svgSource.replace("  <defs>", `${motionStyle}  <defs>`));
  console.log(`Generated ${path.join(buildDir, "icon-animated.svg")}`);
}

fs.copyFileSync(iconPngPath, path.join(rootDir, "website/public/icon.png"));
console.log(`Generated ${iconPngPath}`);

// PNG is also the Windows/Linux packaging source. ICNS requires macOS tools.
if (process.platform !== "darwin") {
  console.log("Run on macOS to regenerate build/icon.icns as well.");
  process.exit(0);
}

const iconsetDir = path.join(buildDir, "icon.iconset");
fs.rmSync(iconsetDir, { recursive: true, force: true });
fs.mkdirSync(iconsetDir, { recursive: true });

for (const size of [16, 32, 128, 256, 512]) {
  const double = size * 2;
  execFileSync(
    "sips",
    ["-z", String(size), String(size), iconPngPath, "--out", path.join(iconsetDir, `icon_${size}x${size}.png`)],
    { stdio: "ignore" }
  );
  execFileSync(
    "sips",
    [
      "-z",
      String(double),
      String(double),
      iconPngPath,
      "--out",
      path.join(iconsetDir, `icon_${size}x${size}@2x.png`)
    ],
    { stdio: "ignore" }
  );
}

execFileSync("iconutil", ["-c", "icns", iconsetDir, "-o", path.join(buildDir, "icon.icns")], {
  stdio: "inherit"
});
fs.rmSync(iconsetDir, { recursive: true, force: true });

console.log(`Generated ${path.join(buildDir, "icon.icns")}`);
